### ISSUE TITLE
Remove unused `maximum_passkeys_per_user`; not the gem's concern

### ISSUE THREAD

**Issue by tcannonfodder** [ruby-passkeys/devise-passkeys#16]
The `:maximum_passkeys_per_user` attribute is legacy code from the early experiments in the gem (see: https://github.com/ruby-passkeys/devise-passkeys/blob/main/lib/devise/passkeys/passkey_issuer.rb#L38).

And validations/limits on the number of passkeys that can be created should be handled by the app itself. This keeps the gem focused, reduces our maintenance overhead, and gives implementors control over the exact behavior

**Comment by johalloran01** [comment]
@tcannonfodder I can take this issue when I return home.

**Comment by johalloran01** [comment]
Created a pull request for this issue: https://github.com/ruby-passkeys/devise-passkeys/pull/41
