### ISSUE TITLE
Reviewing & Editing the Usage section in the README

### ISSUE THREAD

**Issue by tcannonfodder** [ruby-passkeys/devise-passkeys#19]
- [ ] Improving the header structure for better linking to sections
- [ ] Documentation about how/why `relying_party` and `set_relying_party_in_request_env` must be implemented by the app for its controllers; example of using a concern to centralize the logic.

**Comment by johalloran01** [comment]
@tcannonfodder I can take this issue

**Comment by johalloran01** [comment]
@tcannonfodder can I get a clarification on how you want this header structure to be improved? I'm looking through the readme and I'm seeing all major headings utilizing H1 notation for mark down. 

Is there some sub headings you want me to improve on?
