### ISSUE TITLE
Test suite failing because of mismatched "Translation missing" messages

### ISSUE THREAD

**Issue by johalloran01** [ruby-passkeys/devise-passkeys#5]
# Description

Attempted to run `bundle exec appraisal rake test` after installing the required gems using `bundle exec appraisal install`.

However, the test suite failed, with differences in the `Translation missing` error messages. For example:

```
Failure:
Devise::Passkeys::Controllers::TestReauthenticationControllerConcern#test_#reauthenticate:_user_not_verified [/devise-passkeys/test/devise/passkeys/controllers/test_reauthentication_controller_concern.rb:128]:
--- expected
+++ actual
@@ -1 +1,3 @@
-{"error"=>"translation missing: en.devise.failure.user.webauthn_user_verified_verification_error"}
+{"error"=>"Translation missing. Options considered were:
+- en.devise.failure.user.webauthn_user_verified_verification_error
+- en.devise.failure.webauthn_user_verified_verification_error"}
```

# Environment
- Rails Version 7.0.5
- WSL2 Linux (Ubuntu 20.04)

# Screenshots/Files
![Screenshot 2023-06-13 161554](https://github.com/ruby-passkeys/devise-passkeys/assets/65722241/94d3c83b-a26f-4164-9085-1fe81877f77c)

## Test output
[test-run.log](https://github.com/ruby-passkeys/devise-passkeys/files/11738924/message.txt)

**Comment by tcannonfodder** [comment]
It looks like this is a ripple effect of `i18n` version `1.14.0` https://github.com/rails/rails/issues/48377
